[web]
  title = "EPC Mobile PWA"
  host = "0.0.0.0"
  port = 8910
  apiUrl = "http://localhost:8911" # you can customise graphql and dbauth urls individually too: see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths
  includeEnvironmentVariables = [] # any ENV vars that should be available to the web side, see https://redwoodjs.com/docs/environment-variables#web
[api]
  host = "0.0.0.0"
  port = 8911
