version: "3.9"
services:
  api:
    env_file: .env
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8911:8911"
    environment:
      DATABASE_URL: 'file:./dev.db'
  web:
    env_file: .env
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "8910:8910"
    environment:
      REDWOOD_API_URL: 'http://api:8911'